### ISSUE TITLE
Cooking Table/Books not picking up recipes

### ISSUE THREAD

**Issue by DrParadox7** [GTNewHorizons/CookingForBlockheads#23]
@miozune Shaped & Shapeless recipes are no longer being picked up properly with the latest commits.

**Before:** (1.2.5-GTNH)
![image](https://user-images.githubusercontent.com/47131096/148380134-711ee38f-fd3e-49c7-a9b1-bad444ecc033.png)

**After:** (Build 32 from Jenkins)
![image](https://user-images.githubusercontent.com/47131096/148380174-8b18aa90-53af-417a-bc27-995607a1ce73.png)

**Ingredients in the Fridge:**
![image](https://user-images.githubusercontent.com/47131096/148380236-103cedd3-2977-4fe4-9d7f-27c301b296b3.png)

**Comment by DrParadox7** [comment]
**Cooking for Blockheads: #NoFilter Edition** VS **Not Enough Items-GTNH**:
![image](https://user-images.githubusercontent.com/47131096/148388241-df83b5b4-a540-4c21-b709-dcf464a9116c.png)

**Comment by miozune** [comment]
bug confirmed
