### ISSUE TITLE
Sugar (and other GT Tool recipes?) recipe broken

### ISSUE THREAD

**Issue by YannickMG** [GTNewHorizons/CookingForBlockheads#27]
PR #13 looks like it made it impossible to craft sugar at the cooking table using a mortar, as it complains about "Missing tools to craft".

![image](https://user-images.githubusercontent.com/5321549/149667608-f3c94f31-d394-4676-8f2a-c3ac611767bc.png)

**Comment by fleefie** [comment]
Still persists on  2.1.2.4-18-pre :(
