### ISSUE TITLE
Cooking table GUI rendering glitch with resource pack

### ISSUE THREAD

**Issue by cottonman132** [GTNewHorizons/CookingForBlockheads#37]
I have encountered a visual glitch where the cooking table GUI is not rendering properly due to a resource pack I am using. The resource pack in question being [Modernity](https://www.curseforge.com/minecraft/texture-packs/modernity).

![image](https://user-images.githubusercontent.com/64047855/220769836-5ae58984-707a-42cc-b53a-cf36415c9d54.png)

How to replicate:
-Enable resource pack
-Open cooking table GUI (same issue happens with the cooking books as well)

**Comment by miozune** [comment]
Report to the author of the resource pack. CFB for MC [1.7.10](https://github.com/TwelveIterationMods/CookingForBlockheads/blob/1.7.10/src/main/resources/assets/cookingbook/textures/gui/gui.png) and [1.8.9](https://github.com/TwelveIterationMods/CookingForBlockheads/blob/1.8.9/src/main/resources/assets/cookingforblockheads/textures/gui/gui.png) use different texture. I guess there're more mods that use different textures between MC 1.6 and 1.8...
